---
- name: Ensure instance is absent
  amazon.aws.ec2_instance:
    region: "{{ compile_region }}"
    state: absent
    filters:
      tag:Name: "{{ compile_instance_name }}"
  register: _aws_instance_destroy
