---
- name: Launch instance
  amazon.aws.ec2_instance:
    key_name: "{{ createec_keypair }}"
    security_group: "{{ createec_security_group }}"
    instance_type: "{{ createec_instance_type }}"
    image_id: "{{ createec_image }}"
    wait: true
    region: "{{ compile_region }}"
    vpc_subnet_id: subnet-086194c049813830f
    network:
      assign_public_ip: true
    name: "{{ compile_instance_name }}"
  register: ec2
